config/routes.rb
Babyurl::Application.routes.draw do
  get "home/index"

  resources :urls
  match 'urls/increase_count/:id' => 'urls#increase_count'  
  match ':url_out' => 'urls#increase_count'

  root :to => "home#index"

end

app/models/url.rb
class Url < ActiveRecord::Base
  require 'open-uri'
  validates :url_in, :uniqueness => true

  def minimize target_length
    rand(36**target_length).to_s(36)
  end

  def is_valid
    begin 
      open self.url_in
      return true
    rescue
      return false
    end   
  end

  def max_click_nb
    self.clicks_in_previous_week.split(",").max.to_i 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  # GET /urls
  # GET /urls.json

#Not used
  def index
    @urls = Url.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @urls }
    end
  end

  # GET /urls/1
  # GET /urls/1.json
  def show
    @url = Url.find(params[:id])
    max_value = (@url.max_click_nb == 0) ? 1 : @url.max_click_nb
    
    @clicks_chart = Gchart.line(  :size => '550x300', 
              :title => "",
              :bg => {:color => 'AEE9F2'},
              :data => [@url.clicks_in_previous_week.split(",")[6].to_i, @url.clicks_in_previous_week.split(",")[5].to_i, @url.clicks_in_previous_week.split(",")[4].to_i, @url.clicks_in_previous_week.split(",")[3].to_i, @url.clicks_in_previous_week.split(",")[2].to_i, @url.clicks_in_previous_week.split(",")[1].to_i, @url.clicks_in_previous_week.split(",")[0].to_i],
              :line_colors => "00BAD6",
              :axis_with_labels => 'x,y',
              :axis_labels => ['6 days|5 days|4 days|3 days|2 days ago|yesterday|today', "0|#{max_value}"])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @url }
    end
  end

  # POST /urls
  # POST /urls.json
  def create
        @url = Url.new(params[:url])
        if @url.is_valid
          url_in_db = Url.find_by_url_in(@url.url_in) 
          if !url_in_db.nil?
            redirect_to :action => "show", :id => url_in_db.id
          else  
            new_url = @url.minimize(8)
            until Url.find_by_url_out(new_url).nil? do
              new_url = @url.minimize(8)
            end
    
            @url.url_out = "babyurl.heroku.com/#{new_url}"
            @url.out = new_url
            @url.clicks_in_previous_week = "1,0,0,0,0,0,0"
            @url.click_number = 1
            @url.daily_click_number = 1
            if @url.save      
              redirect_to :action => "show", :id => @url.id 
            end
          end
        else
          render 'urls/error'
        end  
  end

  # DELETE /urls/1
  # DELETE /urls/1.json
  def destroy
    @url = Url.find(params[:id])
    @url.destroy

    respond_to do |format|
      format.html { redirect_to urls_url }
      format.json { head :no_content }
    end
  end

  def increase_count
    if !params[:id].blank?
      url = Url.find(:first, :conditions => "id = #{params[:id]}")
    end
    if url.nil?
      url = Url.find_by_out(params[:url_out])
    end
    url.click_number = url.click_number + 1
    url.daily_click_number = url.daily_click_number + 1
    week_clicks_array = url.clicks_in_previous_week.split(",")
    week_clicks_array[0] = url.daily_click_number
    url.clicks_in_previous_week = week_clicks_array.join(",")
    url.save
    redirect_to url.url_in  
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/home/index.html.erb
<div class="content-container">
  <div class="top">
    <h1>BabyUrl - a solution for minimizing Urls</h1>
  </div>  

  <div class="middle">

    <div id="input-banner">
      Babify can help you reduce the length of any Url in just one click!
    </div>

    <div id="form-container">
      <form accept-charset="UTF-8" action="/urls" method="post">
        <input type="text" name="url[url_in]" id="input-url" title="Enter here the url you want to babify" />
        <input id="submit" type="submit" value="Babify the Url" /> 
      </form>
    </div>

    <div id="list">
      <div class="element" id="first">Enter a long Url</div>
      <div class="element" id="second">Click the "Babify" button</div>
      <div class="element" id="third">Get your new link and track how much it is used</div>
      <div class="element" id="fourth">Voila!</div>
    </div>
  </div>

  <div id="footer">
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Babyurl</title>
  <%= stylesheet_link_tag "application", "global", :media => "all" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/urls/_form.html.erb
<%= form_for(@url) do |f| %>
  <% if @url.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@url.errors.count, "error") %> prohibited this url from being saved:</h2>

      <ul>
      <% @url.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url_in %><br />
    <%= f.text_area :url_in %>
  </div>
  <div class="field">
    <%= f.label :url_out %><br />
    <%= f.text_field :url_out %>
  </div>
  <div class="field">
    <%= f.label :http_status %><br />
    <%= f.number_field :http_status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/urls/edit.html.erb
<h1>Editing url</h1>

<%= render 'form' %>

<%= link_to 'Show', @url %> |
<%= link_to 'Back', urls_path %>

app/views/urls/error.html.erb
<div class="error-container">
  <div class="top">
    <h1> Oops ! The link you provided is not valid and thus can't be Babyfied ! </h1>
  </div>
  <div class="element" id="back-error"><a href="/">Back</a></div>
</div>

app/views/urls/index.html.erb
<h1>Listing urls</h1>

<table>
  <tr>
    <th>Url in</th>
    <th>Url out</th>
    <th>Http status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @urls.each do |url| %>
  <tr>
    <td><%= url.url_in %></td>
    <td><%= url.url_out %></td>
    <td><%= url.http_status %></td>
    <td><%= link_to 'Show', url %></td>
    <td><%= link_to 'Edit', edit_url_path(url) %></td>
    <td><%= link_to 'Destroy', url, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Url', new_url_path %>

app/views/urls/new.html.erb
<h1>New url</h1>

<%= render 'form' %>

<%= link_to 'Back', urls_path %>

app/views/urls/show.html.erb
<!--<p id="notice"><%= notice %></p>-->
<div class="icontent-container">
<div class="top">
  <h1> Your babified url management page </h1>
</div>


<div class="middle">
  <div id="left-show">
    <div id="show-list">
      <label for="first"> Your new Url</label>
      <div class="element" id="first"><a href="/urls/increase_count/<%=@url.id%>"><%= @url.url_out%></a></div>
      <label for="second"> Url Management links</label>
      <div class="element" id="second"><a href="/urls/<%=@url.id%>"> babyurl.heroku.com/url/<%=@url.id%></a></div>
      <div class="element" id="third"><a href="/">Back</a></div>
    </div>

  </div>

  <div id ="right-show">
    <div id="chart-title">
      Number of Clicks Per Day for the past week
    </div>
    <div id="chart">
      <%= image_tag @clicks_chart %>
    </div>
    <div class="clicks">
    </div>
  </div>

</div>

<!--<%= link_to 'Edit', edit_url_path(@url) %>--> 
</div>